const headingTemplates = [
    "Happy Birthday, {name}! 🎂",
    "Cheers to {name}'s Special Day! ✦",
    "Celebrating the Amazing {name}!",
    "To the One and Only {name} ✨",
    "Happiest Birthday, {name}!",
    "Wishing {name} the Best Year Ever!",
    "A Surprise for the Wonderful {name} ❤️",
    "Forever Grateful for {name}!",
    "To my favorite person, {name}!",
    "The world is better with {name} in it.",
    "Sending so much love to {name} today!",
    "{name}, you're simply the best!",
    "A toast to {name}! 🥂",
    "Shine on, {name}! ✨",
    "Happy Level Up Day, {name}! 🎮",
    "To {name}: The Star of the Show!",
    "You're a masterpiece, {name}!",
    "Keep being awesome, {name}!",
    "The best is yet to come, {name}!",
    "You're a legend, {name}!",
    "Happy Birthday to my partner in crime, {name}!",
    "{name}, you make life sweet! 🍭",
    "To the kindest soul, {name}!",
    "Keep sparkling, {name}! ✨",
    "You're my sunshine, {name}!",
    "Happy Birthday, {name}! Stay magical.",
    "Another year of you being you, {name}!",
    "To {name}, with all my love.",
    "You're one in a million, {name}!",
    "Happy Birthday, {name}! Let's celebrate!",
    "Cheers to you, {name}!",
    "May your day be as bright as you, {name}!",
    "Happy Birthday to the beautiful {name}!",
    "To {name}: My favorite human.",
    "You're an inspiration, {name}!",
    "Happy Birthday, {name}! Keep dreaming big.",
    "Sending you a big hug, {name}! 🤗",
    "You're the best thing ever, {name}!",
    "Happy Birthday, {name}! You deserve it all.",
    "To the most talented {name}!",
    "You make my heart happy, {name}!",
    "Happy Birthday, {name}! To many more.",
    "You're a blessing, {name}!",
    "Happy Birthday to the incredible {name}!",
    "To {name}: The highlight of my life.",
    "You're a rockstar, {name}! 🎸",
    "Happy Birthday, {name}! Let's make it epic.",
    "You're pure gold, {name}! 🏆",
    "Happy Birthday, {name}! So glad you're here.",
    "To the wonderful {name}!",
    "You're a diamond, {name}! 💎",
    "Happy Birthday, {name}! Enjoy your day.",
    "You're a gift to us all, {name}!",
    "Happy Birthday, {name}! Stay curious.",
    "To the amazing {name}!",
    "You're a ray of light, {name}!",
    "Happy Birthday, {name}! Love you!",
    "You're simply amazing, {name}!",
    "Happy Birthday, {name}! To the moon and back.",
    "To the one who has my heart, {name}.",
    "You're a dream come true, {name}!",
    "Happy Birthday, {name}! Keep shining.",
    "You're a treasure, {name}!",
    "Happy Birthday, {name}! Wish you the best.",
    "To the special {name}!",
    "You're a force of nature, {name}!",
    "Happy Birthday, {name}! Stay bold.",
    "You're a miracle, {name}!",
    "Happy Birthday, {name}! Celebrate you.",
    "To the talented {name}!",
    "You're a vision, {name}!",
    "Happy Birthday, {name}! Shine bright.",
    "You're a delight, {name}!",
    "Happy Birthday, {name}! Have fun!",
    "To the creative {name}!",
    "You're a joy, {name}!",
    "Happy Birthday, {name}! Be happy.",
    "To the sweet {name}!",
    "You're a star, {name}! 🌟",
    "Happy Birthday, {name}! You're loved.",
    "To the brilliant {name}!",
    "You're a gem, {name}! 💍",
    "Happy Birthday, {name}! Stay true.",
    "To the brave {name}!",
    "You're a hero, {name}!",
    "Happy Birthday, {name}! You're strong.",
    "To the wise {name}!",
    "You're a genius, {name}!",
    "Happy Birthday, {name}! Stay smart.",
    "To the funny {name}!",
    "You're a riot, {name}!",
    "Happy Birthday, {name}! Keep laughing.",
    "To the cool {name}!",
    "You're a vibe, {name}!",
    "Happy Birthday, {name}! Stay chill.",
    "To the beautiful {name}!",
    "You're a queen/king, {name}!",
    "Happy Birthday, {name}! Rule the day.",
    "To the magical {name}!",
    "You're a wizard, {name}! 🧙",
    "Happy Birthday, {name}! Do magic.",
    "To the lovely {name}!",
    "You're a flower, {name}! 🌸",
    "Happy Birthday, {name}! Bloom on.",
    "To the unique {name}!",
    "You're a original, {name}!",
    "Happy Birthday, {name}! Be yourself.",
    "To the precious {name}!",
    "You're a rare find, {name}!",
    "Happy Birthday, {name}! You're special.",
    "To the incredible {name}!",
    "You're a wonder, {name}!",
    "Happy Birthday, {name}! Amaze us.",
    "To the super {name}!",
    "You're a superhero, {name}! 🦸",
    "Happy Birthday, {name}! Save the day.",
    "To the great {name}!",
    "You're a champion, {name}! 🥇",
    "Happy Birthday, {name}! Win big.",
    "To the fantastic {name}!",
    "You're a marvel, {name}!",
    "Happy Birthday, {name}! Be wild.",
    "To the awesome {name}!",
    "You're a blast, {name}! 💥",
    "Happy Birthday, {name}! Explode with joy.",
    "To the groovy {name}!",
    "You're a dancer, {name}! 💃",
    "Happy Birthday, {name}! Dance on.",
    "To the soulful {name}!",
    "You're a singer, {name}! 🎤",
    "Happy Birthday, {name}! Sing loud.",
    "To the artistic {name}!",
    "You're a painter, {name}! 🎨",
    "Happy Birthday, {name}! Color your day.",
    "To the sporty {name}!",
    "You're a player, {name}! ⚽",
    "Happy Birthday, {name}! Score points.",
    "To the geeky {name}!",
    "You're a nerd, {name}! 🤓",
    "Happy Birthday, {name}! Code on.",
    "To the foodie {name}!",
    "You're a chef, {name}! 👨‍🍳",
    "Happy Birthday, {name}! Eat well.",
    "To the travel-loving {name}!",
    "You're a wanderer, {name}! ✈️",
    "Happy Birthday, {name}! Explore more.",
    "To the book-loving {name}!",
    "You're a reader, {name}! 📖",
    "Happy Birthday, {name}! Read on.",
    "To the nature-loving {name}!",
    "You're a camper, {name}! 🏕️",
    "Happy Birthday, {name}! Nature calls.",
    "To the dog-loving {name}!",
    "You're a pup-parent, {name}! 🐶",
    "Happy Birthday, {name}! Woof!",
    "To the cat-loving {name}!",
    "You're a cat-parent, {name}! 🐱",
    "Happy Birthday, {name}! Meow!",
    "To the music-loving {name}!",
    "You're a listener, {name}! 🎧",
    "Happy Birthday, {name}! Play it loud.",
    "To the movie-loving {name}!",
    "You're a critic, {name}! 🎬",
    "Happy Birthday, {name}! Action!",
    "To the coffee-loving {name}!",
    "You're a barista, {name}! ☕",
    "Happy Birthday, {name}! Stay caffeinated.",
    "To the tea-loving {name}!",
    "You're a brewer, {name}! 🍵",
    "Happy Birthday, {name}! Sip on.",
    "To the wine-loving {name}!",
    "You're a connoisseur, {name}! 🍷",
    "Happy Birthday, {name}! Sip back and relax.",
    "To the beer-loving {name}!",
    "You're a enthusiast, {name}! 🍺",
    "Happy Birthday, {name}! Cheers!",
    "To the party-loving {name}!",
    "You're a animal, {name}! 🥳",
    "Happy Birthday, {name}! Party on.",
    "To the homebody {name}!",
    "You're a napper, {name}! 💤",
    "Happy Birthday, {name}! Nap on.",
    "To the early bird {name}!",
    "You're a riser, {name}! 🌅",
    "Happy Birthday, {name}! Rise and shine.",
    "To the night owl {name}!",
    "You're a watcher, {name}! 🦉",
    "Happy Birthday, {name}! Stay up late.",
    "To the fashionista {name}!",
    "You're a model, {name}! 👗",
    "Happy Birthday, {name}! Look sharp.",
    "To the gamer {name}!",
    "You're a pro, {name}! 🕹️",
    "Happy Birthday, {name}! GG!",
    "To the thinker {name}!",
    "You're a philosopher, {name}! 🤔",
    "Happy Birthday, {name}! Think deep.",
    "To the doer {name}!",
    "You're a achiever, {name}! ✅",
    "Happy Birthday, {name}! Get it done.",
    "To the dreamer {name}!",
    "You're a believer, {name}! ☁️",
    "Happy Birthday, {name}! Reach high.",
    "To the lover {name}!",
    "You're a romantic, {name}! ❤️",
    "Happy Birthday, {name}! Spread love.",
    "To the friend {name}!",
    "You're a bestie, {name}! 👫",
    "Happy Birthday, {name}! Always here.",
    "To the family {name}!",
    "You're a sibling/parent, {name}! 🏠",
    "Happy Birthday, {name}! Love you fam.",
    "To the icon {name}!",
    "You're a symbol, {name}! 🆔",
    "Happy Birthday, {name}! Stay classic."
];
